@startuml Authentication Use Case
left to right direction

actor Guest
actor User

rectangle "Authentication" {
    usecase "Register" as UC1
    usecase "Login" as UC2
    usecase "Logout" as UC3
}

UC1 <-- Guest
UC2 <-- Guest
User --> UC3 

@enduml