@startuml User Management Use Case
left to right direction

actor Admin
actor Superadmin

Superadmin <|-- Admin

rectangle "User Management" {
    usecase "View Users" as UC1
    usecase "Edit User" as UC2
    usecase "Delete User" as UC3
    usecase "Change User Role" as UC4
}
    
rectangle "Role Management" {
    usecase "View Roles" as UC5
    usecase "Add Role" as UC6
    usecase "Edit Role" as UC7
    usecase "Delete Role" as UC8
}

Admin --> UC1
Admin --> UC2
Admin --> UC3

Superadmin --> UC4

Superadmin --> UC5
Superadmin --> UC6
Superadmin --> UC7
Superadmin --> UC8

UC4 --> UC5 : <<include>>
@enduml