@startuml order-management-usecase
skinparam linetype spline
left to right direction

actor User
actor Admin
actor LLM

package "Order Management" {
  User --> (Add to Cart)
  User --> (Remove from Cart)
  User --> (Place Order)
  User --> (Cancel Order)
  (Process Order) <-- Admin
  (Add Diagnoses) <-- LLM
  (Process Order) .> (View Orders) : <<include>>
  User --> (View Diagnoses)
  (Add Diagnoses) .> (View Diagnoses) : <<include>>
  (Add to Cart) .> (View Orders) : <<include>>
}
@enduml